### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by vlahx** [phpcodertop/codeigniternewsmagazine#1]
Hello, I tryied to use your code. Install it, configured, everything ok but I cannot understand why I have an white screen when acces /home /admin, or anything. And no erorrs. You may have some ideea what happens. I verifyied the code, controllers, models, views but I did not discover any bugs

**Comment by ahmedhalima** [comment]
@vlahx It was an old version of codeigniter, I've upgraded to codeigniter 3.1.9 
Now you can clone it and there will be no issues , Note sql file included under sql folder
/admin
username: admin
password: admin
